$cndi.comment(external-dns-secret): External DNS Credentials
apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  namespace: external-dns
stringData:
  cloudflare_api_token: $cndi_on_ow.seal_secret_from_env_var(CLOUDFLARE_API_TOKEN)
