$cndi.comment(external-dns-secret): External DNS Credentials
apiVersion: v1
kind: Secret
metadata:
  name: external-dns
  namespace: external-dns
stringData:
  credentials.json: $cndi_on_ow.seal_secret_from_env_var(GOOGLE_CREDENTIALS)
