cndi_version: v2
project_name: mj-ec2-airflow
provider: aws
distribution: microk8s
infrastructure:
  cndi:
    cert_manager:
      email: matt.johnston@polyseam.io
    nodes:
      - name: airflow-alpha
        instance_type: t3.medium
        disk_size: 100
      - name: airflow-beta
        instance_type: t3.medium
        disk_size: 100
cluster_manifests: {}
applications: {}