name: Enhancement
description: Propose some improvement to the core CNDI functionality
# projects: ['polyseam/6'] - this is not supported, but is handled by workflows configured here: https://github.com/orgs/polyseam/projects/6/workflows
title: "[Enhancement]: "
labels: ["enhancement"]
assignees:
  - johnstonmatt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping to improve our CNDI!
        If you are looking to request a new feature to the CNDI framework that is not a Template or a Deployment Target, you're in the right spot!

  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
        What version of our software are you running?
        You can find this information by running `cndi --version`.
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: 'Please provide a summary of the enhancement you are proposing:'
      description: What would change about CNDI if this were implemented?
      placeholder: I think the user experience would be greatly improved if..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: 'Please provide the motivation or use case for this enhancement:'
      description: Why do you think this is a good idea?
      placeholder: "I think this is a good idea because..."
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: How can we best workaround this issue so far?
      description: Is there currently some solution which is not ideal?
      placeholder: Currently, I have to do the following tedious to get around this issue...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: 'How would you approach solving this problem within CNDI?'
      description: How do you imagine this feature would be implemented?
      placeholder: "By creating a dedicated check for foo..."
    validations:
      required: false


  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/polyseam/cndi/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
