// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $llms_txt_index from "./routes/llms.txt/index.tsx";
import * as $Configurator_ConfiguratorCLISnippet from "./islands/Configurator/ConfiguratorCLISnippet.tsx";
import * as $Configurator_ConfiguratorContextProvider from "./islands/Configurator/ConfiguratorContextProvider.tsx";
import * as $Configurator_ConfiguratorGizmo from "./islands/Configurator/ConfiguratorGizmo.tsx";
import * as $Configurator_ConfiguratorGizmoContext from "./islands/Configurator/ConfiguratorGizmoContext.tsx";
import * as $Configurator_ConfiguratorPromptField from "./islands/Configurator/ConfiguratorPromptField.tsx";
import * as $Configurator_FormPanel from "./islands/Configurator/FormPanel.tsx";
import * as $Configurator_asyncReplace from "./islands/Configurator/asyncReplace.ts";
import * as $Configurator_conditionals from "./islands/Configurator/conditionals.ts";
import * as $Configurator_fields_Confirm from "./islands/Configurator/fields/Confirm.tsx";
import * as $Configurator_fields_File from "./islands/Configurator/fields/File.tsx";
import * as $Configurator_fields_Input from "./islands/Configurator/fields/Input.tsx";
import * as $Configurator_fields_Select from "./islands/Configurator/fields/Select.tsx";
import * as $Configurator_macros from "./islands/Configurator/macros.ts";
import * as $Configurator_responseValidators from "./islands/Configurator/responseValidators.ts";
import * as $Configurator_shared from "./islands/Configurator/shared.ts";
import * as $LinkOut from "./islands/LinkOut.tsx";
import * as $SourceShower from "./islands/SourceShower.tsx";
import * as $TemplateSelector from "./islands/TemplateSelector.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/llms.txt/index.tsx": $llms_txt_index,
  },
  islands: {
    "./islands/Configurator/ConfiguratorCLISnippet.tsx":
      $Configurator_ConfiguratorCLISnippet,
    "./islands/Configurator/ConfiguratorContextProvider.tsx":
      $Configurator_ConfiguratorContextProvider,
    "./islands/Configurator/ConfiguratorGizmo.tsx":
      $Configurator_ConfiguratorGizmo,
    "./islands/Configurator/ConfiguratorGizmoContext.tsx":
      $Configurator_ConfiguratorGizmoContext,
    "./islands/Configurator/ConfiguratorPromptField.tsx":
      $Configurator_ConfiguratorPromptField,
    "./islands/Configurator/FormPanel.tsx": $Configurator_FormPanel,
    "./islands/Configurator/asyncReplace.ts": $Configurator_asyncReplace,
    "./islands/Configurator/conditionals.ts": $Configurator_conditionals,
    "./islands/Configurator/fields/Confirm.tsx": $Configurator_fields_Confirm,
    "./islands/Configurator/fields/File.tsx": $Configurator_fields_File,
    "./islands/Configurator/fields/Input.tsx": $Configurator_fields_Input,
    "./islands/Configurator/fields/Select.tsx": $Configurator_fields_Select,
    "./islands/Configurator/macros.ts": $Configurator_macros,
    "./islands/Configurator/responseValidators.ts":
      $Configurator_responseValidators,
    "./islands/Configurator/shared.ts": $Configurator_shared,
    "./islands/LinkOut.tsx": $LinkOut,
    "./islands/SourceShower.tsx": $SourceShower,
    "./islands/TemplateSelector.tsx": $TemplateSelector,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
