apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $cndi.get_arg(ingress_name) }}"
  namespace: "{{ $cndi.get_arg(namespace) }}"
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    external-dns.alpha.kubernetes.io/hostname: "{{ $cndi.get_arg(hostname) }}"
    $cndi.comment(unmanaged_target_description): "if you are using an unmanaged Kubernetes distribution, you can uncomment the following line and replace the value with your load balancer hostname"
    $cndi.comment(unmanaged_target): "external-dns.alpha.kubernetes.io/target: my-loadbalancer.us-east-1.elb.amazonaws.com"
spec:
  ingressClassName: "{{ $cndi.get_arg(ingress_class_name) }}"
  tls:
    - hosts:
        - "{{ $cndi.get_arg(hostname) }}"
      secretName: cluster-issuer-private-key
  rules:
    - host: "{{ $cndi.get_arg(hostname) }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ $cndi.get_arg(service_name) }}"
                port:
                  number: "{{ $cndi.get_arg(service_port) }}"